# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 02:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(blank=True, max_length=128)),
                ('tmdb_id', models.CharField(max_length=128, unique=True)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('title', models.TextField(blank=True)),
                ('logline', models.TextField(blank=True)),
                ('no_seasons', models.IntegerField(null=True)),
                ('no_episodes', models.IntegerField(null=True)),
                ('runtime_per_episode', models.IntegerField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('imdb_rating', models.FloatField(null=True)),
                ('rt_rating', models.FloatField(null=True)),
                ('director', models.CharField(blank=True, max_length=128)),
                ('trailer_link', models.CharField(blank=True, max_length=128)),
                ('image_link', models.CharField(blank=True, max_length=128)),
                ('topic_one', models.CharField(blank=True, max_length=128)),
                ('topic_two', models.CharField(max_length=128, null=True)),
                ('on_netflix', models.BooleanField(default=False)),
                ('on_amazon', models.BooleanField(default=False)),
                ('on_hulu', models.BooleanField(default=False)),
                ('on_hbo', models.BooleanField(default=False)),
                ('on_other', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Content')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tag_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.ManyToManyField(through='api.ServiceContent', to='api.Content'),
        ),
        migrations.AddField(
            model_name='service',
            name='users',
            field=models.ManyToManyField(through='api.UserSubscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tag'),
        ),
        migrations.AddField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(through='api.ContentTag', to='api.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=set([('user', 'service')]),
        ),
        migrations.AlterUniqueTogether(
            name='servicecontent',
            unique_together=set([('content', 'service')]),
        ),
        migrations.AlterUniqueTogether(
            name='contenttag',
            unique_together=set([('content', 'tag')]),
        ),
    ]
