# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.ManyToManyField(through='api.ServiceContent', to='api.Content'),
        ),
    ]
