# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170712_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='chump_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='discovery_mode',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='content',
            name='in_set',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='keywords_list',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='primary_mode',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(default='', through='api.ContentTag', to='api.Tag'),
        ),
    ]
