# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
