# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 00:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20170709_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='content',
            name='trailer',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='contenttag',
            unique_together=set([('content', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='servicecontent',
            unique_together=set([('content', 'service')]),
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=set([('user', 'service')]),
        ),
    ]
