# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_content_keywords_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_link',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='content',
            name='trailer_link',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
