# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content_type', models.CharField(max_length=128)),
                ('services', models.ManyToManyField(to='api.Service')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
