# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tag_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='test',
        ),
    ]
