# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_tag_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='rt_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
