# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170723_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usercontent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='service',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='users',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserContent',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
