# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170723_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='contenttag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contenttag',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contenttag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='service',
            name='content',
        ),
        migrations.AlterUniqueTogether(
            name='servicecontent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='servicecontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='servicecontent',
            name='service',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='ContentTag',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceContent',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
