# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(choices=[('explore_tag_selected', 'Explore Tag Selected'), ('watchlist_viewed', 'Watchlist Viewed'), ('explore_mode_selected', 'Explore Mode Selected')], max_length=100),
        ),
    ]
