# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170723_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontent',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='was_on_watchlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='watching_now',
            field=models.BooleanField(default=False),
        ),
    ]
