# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170808_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='broadcast_response_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userlog',
            name='weekly_rec_response',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(choices=[('explore_tag_selected', 'Explore Tag Selected'), ('watchlist_viewed', 'Watchlist Viewed'), ('explore_mode_selected', 'Explore Mode Selected'), ('watchlist_add', 'Watchlist Add'), ('already_seen_add', 'Already Seen Add'), ('broadcast_response', 'Broadcast Response'), ('user_shared', 'User Shared'), ('weekly_rec_action', 'Weekly Rec Action')], max_length=100),
        ),
    ]
