# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicecontent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='servicecontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='servicecontent',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceContent',
        ),
    ]
