# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
