# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
