# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='leaving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='leaving_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
