# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170725_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='content',
            name='leaving',
        ),
        migrations.RemoveField(
            model_name='content',
            name='leaving_date',
        ),
        migrations.RemoveField(
            model_name='content',
            name='updated_date',
        ),
    ]
