# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170727_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
