# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='added_date',
        ),
    ]
